/* Moja Droga — sekcja Islam: tlumaczenia (IS) + dane (teksty modlitw, alfabet, ENTRIES, miasta) */
'use strict';

/* ══════════════════════════════
   ISLAM — TRANSLATIONS
══════════════════════════════ */
var IS={
  pl:{appTitle:'Moja Droga',appSub:'Notatnik drogi w islamie',pv2:'2 rakaty',pv3:'3 rakaty',pv4:'4 rakaty',pwMethod:'MWL · przybliżone',changeCity:'Zmień miasto',searchCity:'Szukaj…',now:'Teraz',next:'Następna',between:'między modlitwami',inTime:'za',listHeader:'Twój notatnik',settings:'Ustawienia',dataLbl:'Twoje dane',exportBtn:'Eksportuj dane (JSON)',importBtn:'Importuj dane (JSON)',setNote:'Dane są zapisywane lokalnie w tej przeglądarce. Eksport pozwala przenieść je na inne urządzenie lub zrobić kopię zapasową.',importOk:'Dane zaimportowane pomyślnie.',importErr:'Nieprawidłowy plik — import nie powiódł się.',doneOn:'Oznaczono jako opanowane ✓',doneOff:'Cofnięto oznaczenie',day1:'dzień z rzędu',dayN:'dni z rzędu',profT:'Twoje postępy',profBest:'rekord',profPray:'Modlitwy (Salah)',profPToday:'dziś',profPMonth:'w tym miesiącu',profPStreak:'seria dni 5/5',profHeat:'Ostatnie 6 tygodni',profLess:'mniej',profMore:'więcej',profRule:'Dzień liczy się do serii od 2 aktywności — czytanie, odhaczanie i odnotowane modlitwy.',ptBtn:'Pomodliłem się',ptSure:'Na pewno?',ptUndo:'Cofnąć?',ptOn:'Modlitwa odnotowana ✓',ptOff:'Odznaczono modlitwę',ptToggle:'Modlitwy',msP5:'☾ 5/5 modlitw dziś — Alhamdulillah!',msP7:'☾ 7 dni z rzędu z kompletem modlitw!',statsDays:'dni z aplikacją',statsDone:'opanowanych',ms7:'☾ 7 dni z rzędu — tak trzymaj!',msAll:'🎉 Cały temat opanowany!',ms100:'💯 100 opanowanych elementów!',installLbl:'Aplikacja na telefonie',installBtn:'Zainstaluj',installIos:'iPhone/iPad: Udostępnij → „Dodaj do ekranu głównego”',importConfirm:'Import nadpisze obecne dane. Kontynuować?',errGeneric:'Coś poszło nie tak',saveErr:'Nie udało się zapisać postępu',goalLbl:'Cel dzienny (aktywności)',goalToday:'Dziś',goalDone:'Cel dzienny osiągnięty — tak trzymaj!',remindPray:'Za 10 minut',streakWarn:'Twoja seria wygaśnie o północy — wystarczy jedna aktywność',wakeLbl:'Nie gaś ekranu w widoku modlitwy',wakeOn:'Włączone',wakeOff:'Wyłączone',shareLbl:'Udostępnij postęp',shareBtn:'Udostępnij',shareText:'Moja Droga — seria {st} dni, {done} opanowanych elementów.',aboutLbl:'O aplikacji',aboutVer:'Wersja',aboutContent:'Treść: {n} wpisów islamskich · {t} tematów angielskiego',aboutRepo:'Repozytorium projektu',dangerLbl:'Strefa ryzyka',resetBtn:'Wyczyść wszystkie dane',resetSure:'Na pewno? Kliknij ponownie',resetDone:'Dane wyczyszczone',backupNever:'Kopia zapasowa: jeszcze nie robiona',backupDays:'Ostatnia kopia zapasowa: {d} dni temu',backupAsk:'Warto zrobić kopię zapasową — dane są tylko w tej przeglądarce',offlineMsg:'Jesteś offline — aplikacja działa z pamięci podręcznej',copied:'Skopiowano do schowka'},
  en:{appTitle:'My Path',appSub:'Notebook of my journey in Islam',pv2:"2 rak'ahs",pv3:"3 rak'ahs",pv4:"4 rak'ahs",pwMethod:'MWL · approximate',changeCity:'Change city',searchCity:'Search…',now:'Now',next:'Next',between:'between prayers',inTime:'in',listHeader:'Your notebook',settings:'Settings',dataLbl:'Your data',exportBtn:'Export data (JSON)',importBtn:'Import data (JSON)',setNote:'Data is stored locally in this browser. Export lets you move it to another device or keep a backup.',importOk:'Data imported successfully.',importErr:'Invalid file — import failed.',doneOn:'Marked as mastered ✓',doneOff:'Mark removed',day1:'day streak',dayN:'day streak',profT:'Your progress',profBest:'best streak',profPray:'Prayers (Salah)',profPToday:'today',profPMonth:'this month',profPStreak:'full 5/5 days in a row',profHeat:'Last 6 weeks',profLess:'less',profMore:'more',profRule:'A day counts towards the streak from 2 activities — reading, ticking off and marking prayers.',ptBtn:'I prayed',ptSure:'Sure?',ptUndo:'Undo?',ptOn:'Prayer marked ✓',ptOff:'Prayer unmarked',ptToggle:'Prayers',msP5:'☾ All 5 prayers today — Alhamdulillah!',msP7:'☾ 7 days in a row with all prayers!',statsDays:'days active',statsDone:'mastered',ms7:'☾ 7 days in a row — keep it up!',msAll:'🎉 Whole topic mastered!',ms100:'💯 100 items mastered!',installLbl:'App on your phone',installBtn:'Install',installIos:'iPhone/iPad: Share → “Add to Home Screen”',importConfirm:'Import will overwrite current data. Continue?',errGeneric:'Something went wrong',saveErr:'Could not save progress',goalLbl:'Daily goal (activities)',goalToday:'Today',goalDone:'Daily goal reached — keep it up!',remindPray:'In 10 minutes',streakWarn:'Your streak expires at midnight — one activity is enough',wakeLbl:'Keep the screen awake in the prayer view',wakeOn:'On',wakeOff:'Off',shareLbl:'Share progress',shareBtn:'Share',shareText:'My Path — {st}-day streak, {done} items mastered.',aboutLbl:'About',aboutVer:'Version',aboutContent:'Content: {n} Islamic entries · {t} English topics',aboutRepo:'Project repository',dangerLbl:'Danger zone',resetBtn:'Clear all data',resetSure:'Sure? Click again',resetDone:'Data cleared',backupNever:'Backup: none yet',backupDays:'Last backup: {d} days ago',backupAsk:'Consider a backup — data lives only in this browser',offlineMsg:'You are offline — the app runs from cache',copied:'Copied to clipboard'}
};
var PL_N={fajr:{pl:'Fajr',en:'Fajr'},sunrise:{pl:'Wschód',en:'Sunrise'},dhuhr:{pl:'Dhuhr',en:'Dhuhr'},asr:{pl:'Asr',en:'Asr'},maghrib:{pl:'Maghrib',en:'Maghrib'},isha:{pl:'Isha',en:'Isha'}};
function it(k){return IS[ST.lang][k]||k;}
function rl(item){
  if(typeof item==='string')return item;
  if(item&&item.phrase!==undefined)return item.phrase+' '+item.note[ST.lang];
  if(item&&item.pl!==undefined)return item[ST.lang];
  return '';
}

/* ── ISLAM DATA ── */
var fatiha=['Bismillah ir-Rahman ir-Rahim','Alhamdu lillahi Rabbil-\'alamin','Ar-Rahman ir-Rahim','Maliki yawmid-din','Iyyaka na\'budu wa iyyaka nasta\'in','Ihdinas-siratal-mustaqim','Siratal-ladhina an\'amta \'alayhim','Ghayril-maghdubi \'alayhim wa lad-dallin','Amin'];
var ikhlas=['Qul huwa Allahu ahad','Allahu-s-Samad','Lam yalid wa lam yulad','Wa lam yakun lahu kufuwan ahad'];
var wudu=[{pl:'Niyyah (intencja w sercu):',en:'Niyyah (intention in the heart):'},{pl:'Bismillah',en:'Bismillah'},{pl:'Mycie rąk 3x (do nadgarstka)',en:'Wash hands 3x (to wrist)'},{pl:'Płukanie ust 3x',en:'Rinse mouth 3x'},{pl:'Płukanie nosa 3x',en:'Rinse nose 3x'},{pl:'Mycie twarzy 3x',en:'Wash face 3x'},{pl:'Mycie prawego przedramienia 3x, potem lewego',en:'Wash right forearm 3x, then left'},{pl:'Przetarcie głowy (masah) — raz',en:'Wipe head (masah) — once'},{pl:'Przetarcie uszu — raz',en:'Wipe ears — once'},{pl:'Mycie prawej stopy 3x, potem lewej',en:'Wash right foot 3x, then left'},'Ash-hadu al la ilaha illallah, wa ash-hadu anna Muhammadan \'abduhu wa rasuluh'];
var shahada=['Ash-hadu al la ilaha illallah','Wa ash-hadu anna Muhammadan rasulullah',{pl:'Znaczenie: Zaświadczam, że nie ma bóstwa oprócz Allaha, i że Muhammad jest Jego wysłannikiem.',en:'Meaning: I bear witness that there is no god but Allah, and that Muhammad is His messenger.'}];
var arLetters=[{ar:'ا',l:{pl:'Alif',en:'Alif'}},{ar:'ب',l:{pl:'Ba',en:'Ba'}},{ar:'ت',l:{pl:'Ta',en:'Ta'}},{ar:'ث',l:{pl:'Tha',en:'Tha'}},{ar:'ج',l:{pl:'Dżim',en:'Jim'}},{ar:'ح',l:{pl:'Ha (twarde)',en:'Ha (heavy)'}},{ar:'خ',l:{pl:'Cha',en:'Kha'}},{ar:'د',l:{pl:'Dal',en:'Dal'}},{ar:'ذ',l:{pl:'Dzal',en:'Dhal'}},{ar:'ر',l:{pl:'Ra',en:'Ra'}},{ar:'ز',l:{pl:'Zaj',en:'Zay'}},{ar:'س',l:{pl:'Sin',en:'Sin'}},{ar:'ش',l:{pl:'Szin',en:'Shin'}},{ar:'ص',l:{pl:'Sad',en:'Sad'}},{ar:'ض',l:{pl:'Dad',en:'Dad'}},{ar:'ط',l:{pl:'Ta (twarde)',en:'Ta (heavy)'}},{ar:'ظ',l:{pl:'Za (twarde)',en:'Za (heavy)'}},{ar:'ع',l:{pl:'Ajn',en:"'Ayn"}},{ar:'غ',l:{pl:'Ghajn',en:'Ghayn'}},{ar:'ف',l:{pl:'Fa',en:'Fa'}},{ar:'ق',l:{pl:'Qaf',en:'Qaf'}},{ar:'ك',l:{pl:'Kaf',en:'Kaf'}},{ar:'ل',l:{pl:'Lam',en:'Lam'}},{ar:'م',l:{pl:'Mim',en:'Mim'}},{ar:'ن',l:{pl:'Nun',en:'Nun'}},{ar:'ه',l:{pl:'Ha (lekkie)',en:'Ha (light)'}},{ar:'و',l:{pl:'Waw',en:'Waw'}},{ar:'ي',l:{pl:'Ja',en:'Ya'}}];
var istiftah=['Subhanaka Allahumma wa bihamdika','Wa tabarakasmuka wa ta\'ala jadduka','Wa la ilaha ghayruk'];
var tahijjat=['At-tahiyyatu lillahi was-salawatu wat-tayyibatu','Assalamu \'alayka ayyuhan-Nabiyyu wa rahmatullahi wa barakatuh','Assalamu \'alayna wa \'ala \'ibadillahis-salihin','Ash-hadu al la ilaha illallah wa ash-hadu anna Muhammadan \'abduhu wa rasuluh'];
var salawat=['Allahumma salli \'ala Muhammad wa \'ala aali Muhammad','Kama sallayta \'ala Ibrahima wa \'ala aali Ibrahim','Innaka Hamidun Majid','Allahumma barik \'ala Muhammad wa \'ala aali Muhammad','Kama barakta \'ala Ibrahima wa \'ala aali Ibrahim','Innaka Hamidun Majid'];
var taslim=[{phrase:'Assalamu \'alaykum wa rahmatullah',note:{pl:'(w prawo)',en:'(right)'}},{phrase:'Assalamu \'alaykum wa rahmatullah',note:{pl:'(w lewo)',en:'(left)'}}];
function psec(lp,le,lines,hl){return{lp:lp,le:le,lines:lines,hl:!!hl};}
function pcycle(n,addSura){var s=[];s.push(psec('Rakat '+n+' — Al-Fatiha','Rak\'ah '+n+' — Al-Fatiha',fatiha));if(addSura)s.push(psec('Rakat '+n+' — sura','Rak\'ah '+n+' — surah',[{pl:'(dowolna krótka sura)',en:'(any short surah)'}]));s.push(psec('Rakat '+n+' — ruku','Rak\'ah '+n+' — ruku',['Allahu Akbar','Subhana Rabbiyal-\'Azim (x3)']));s.push(psec('Rakat '+n+' — powrót','Rak\'ah '+n+' — rising',['Sami\' Allahu liman hamidah','Rabbana wa lakal-hamd']));s.push(psec('Rakat '+n+' — sudżud 1','Rak\'ah '+n+' — sujud 1',['Allahu Akbar','Subhana Rabbiyal-A\'la (x3)']));s.push(psec('Rakat '+n+' — siad','Rak\'ah '+n+' — sitting',['Allahu Akbar','Rabbighfir li (x2)']));s.push(psec('Rakat '+n+' — sudżud 2','Rak\'ah '+n+' — sujud 2',['Allahu Akbar','Subhana Rabbiyal-A\'la (x3)']));return s;}
function openBlock(){var s=[];s.push(psec('Takbiratul ihram','Takbiratul ihram',['Allahu Akbar']));s.push(psec('Dua otwierające (opcjonalnie)','Opening dua (optional)',istiftah));return s;}
function pb2(){var s=openBlock();s=s.concat(pcycle(1,true));s.push(psec('Wstanie — rakat 2','Rising — rak\'ah 2',['Allahu Akbar']));s=s.concat(pcycle(2,true));s.push(psec('Siad końcowy — tashahhud','Final sitting — tashahhud',tahijjat,true));s.push(psec('Siad końcowy — salawat','Final sitting — salawat',salawat,true));s.push(psec('Taslim','Taslim',taslim));return s;}
function pb3(){var s=openBlock();s=s.concat(pcycle(1,true));s.push(psec('Wstanie — rakat 2','Rising — rak\'ah 2',['Allahu Akbar']));s=s.concat(pcycle(2,true));s.push(psec('Siad pośredni — tashahhud','Middle sitting — tashahhud',tahijjat,true));s.push(psec('Wstanie — rakat 3','Rising — rak\'ah 3',['Allahu Akbar']));s=s.concat(pcycle(3,false));s.push(psec('Siad końcowy — tashahhud','Final sitting — tashahhud',tahijjat,true));s.push(psec('Siad końcowy — salawat','Final sitting — salawat',salawat,true));s.push(psec('Taslim','Taslim',taslim));return s;}
function pb4(){var s=openBlock();s=s.concat(pcycle(1,true));s.push(psec('Wstanie — rakat 2','Rising — rak\'ah 2',['Allahu Akbar']));s=s.concat(pcycle(2,true));s.push(psec('Siad pośredni — tashahhud','Middle sitting — tashahhud',tahijjat,true));s.push(psec('Wstanie — rakat 3','Rising — rak\'ah 3',['Allahu Akbar']));s=s.concat(pcycle(3,false));s.push(psec('Wstanie — rakat 4','Rising — rak\'ah 4',['Allahu Akbar']));s=s.concat(pcycle(4,false));s.push(psec('Siad końcowy — tashahhud','Final sitting — tashahhud',tahijjat,true));s.push(psec('Siad końcowy — salawat','Final sitting — salawat',salawat,true));s.push(psec('Taslim','Taslim',taslim));return s;}
var psets={'2':pb2(),'3':pb3(),'4':pb4()};
var ENTRIES=[
  {id:'al-fatiha',title:{pl:'Al-Fatiha',en:'Al-Fatiha'},sub:{pl:'1. sura Koranu',en:'1st chapter of the Qur\'an'},type:'list',lines:fatiha},
  {id:'alfabet',title:{pl:'Alfabet arabski',en:'Arabic alphabet'},sub:{pl:'28 liter z transliteracją',en:'28 letters with transliteration'},type:'letters'},
  {id:'wudu',title:{pl:'Wudu (ablucja)',en:'Wudu (ablution)'},sub:{pl:'Oczyszczenie przed modlitwą',en:'Purification before prayer'},type:'list',lines:wudu},
  {id:'shahada',title:{pl:'Szahada',en:'Shahada'},sub:{pl:'Wyznanie wiary — 1. filar islamu',en:'Declaration of faith — 1st pillar'},type:'list',lines:shahada},
  {id:'al-ikhlas',title:{pl:'Al-Ikhlas',en:'Al-Ikhlas'},sub:{pl:'112. sura Koranu',en:'112th chapter of the Qur\'an'},type:'list',lines:ikhlas},
  {id:'modlitwa',title:{pl:'Modlitwa (Salat)',en:'Prayer (Salah)'},sub:{pl:'Pełny tekst — 2, 3 lub 4 rakaty',en:'Full text — 2, 3 or 4 rak\'ahs'},type:'prayer'}
];
function findEntry(id){return ENTRIES.find(function(x){return x.id===id;});}
function canonNum(id){return ENTRIES.findIndex(function(e){return e.id===id;})+1;}

/* ── CITIES ── */
var CITIES=[{id:'krakow',name:'Kraków',lat:50.0647,lon:19.9450,tz:'Europe/Warsaw'},{id:'warszawa',name:'Warszawa',lat:52.2297,lon:21.0122,tz:'Europe/Warsaw'},{id:'gdansk',name:'Gdańsk',lat:54.3520,lon:18.6466,tz:'Europe/Warsaw'},{id:'wroclaw',name:'Wrocław',lat:51.1079,lon:17.0385,tz:'Europe/Warsaw'},{id:'poznan',name:'Poznań',lat:52.4064,lon:16.9252,tz:'Europe/Warsaw'},{id:'lodz',name:'Łódź',lat:51.7592,lon:19.4560,tz:'Europe/Warsaw'},{id:'london',name:'Londyn / London',lat:51.5072,lon:-0.1276,tz:'Europe/London'},{id:'paris',name:'Paryż / Paris',lat:48.8566,lon:2.3522,tz:'Europe/Paris'},{id:'berlin',name:'Berlin',lat:52.5200,lon:13.4050,tz:'Europe/Berlin'},{id:'amsterdam',name:'Amsterdam',lat:52.3676,lon:4.9041,tz:'Europe/Amsterdam'},{id:'istanbul',name:'Stambuł / Istanbul',lat:41.0082,lon:28.9784,tz:'Europe/Istanbul'},{id:'moscow',name:'Moskwa / Moscow',lat:55.7558,lon:37.6173,tz:'Europe/Moscow'},{id:'cairo',name:'Kair / Cairo',lat:30.0444,lon:31.2357,tz:'Africa/Cairo'},{id:'mecca',name:'Mekka / Mecca',lat:21.3891,lon:39.8579,tz:'Asia/Riyadh'},{id:'medina',name:'Medyna / Medina',lat:24.5247,lon:39.5692,tz:'Asia/Riyadh'},{id:'riyadh',name:'Rijad / Riyadh',lat:24.7136,lon:46.6753,tz:'Asia/Riyadh'},{id:'dubai',name:'Dubaj / Dubai',lat:25.2048,lon:55.2708,tz:'Asia/Dubai'},{id:'baghdad',name:'Bagdad / Baghdad',lat:33.3152,lon:44.3661,tz:'Asia/Baghdad'},{id:'karachi',name:'Karaczi / Karachi',lat:24.8607,lon:67.0011,tz:'Asia/Karachi'},{id:'jakarta',name:'Dżakarta / Jakarta',lat:-6.2088,lon:106.8456,tz:'Asia/Jakarta'},{id:'surabaya',name:'Surabaya',lat:-7.2575,lon:112.7521,tz:'Asia/Jakarta'},{id:'kuala',name:'Kuala Lumpur',lat:3.1390,lon:101.6869,tz:'Asia/Kuala_Lumpur'},{id:'ny',name:'Nowy Jork / New York',lat:40.7128,lon:-74.0060,tz:'America/New_York'},{id:'chicago',name:'Chicago',lat:41.8781,lon:-87.6298,tz:'America/Chicago'},{id:'la',name:'Los Angeles',lat:34.0522,lon:-118.2437,tz:'America/Los_Angeles'},{id:'toronto',name:'Toronto',lat:43.6532,lon:-79.3832,tz:'America/Toronto'},{id:'sydney',name:'Sydney',lat:-33.8688,lon:151.2093,tz:'Australia/Sydney'}];
function getCity(){return CITIES.find(function(c){return c.id===ST.cityId;})||CITIES[0];}

